CREATE TABLE "Athlete" (
  "athlete_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Name" varchar(255),
  "Sex" varchar(1),
  "Age" int,
  "AgeClass" varchar(255),
  "BodyweightKg" numeric,
  "Country" varchar(255),
  "Tested" boolean
);

CREATE TABLE "Event" (
  "event_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Event" varchar(255) UNIQUE
);

CREATE TABLE "Equipment" (
  "equipment_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Equipment" varchar(255) UNIQUE
);

CREATE TABLE "Division" (
  "division_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Division" varchar(255) UNIQUE
);

CREATE TABLE "WeightClass" (
  "weightclass_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "WeightClassKg" varchar(50) UNIQUE
);

CREATE TABLE "Lift" (
  "lift_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "athlete_id" int,
  "event_id" int,
  "equipment_id" int,
  "division_id" int,
  "weightclass_id" int,
  "Squat1Kg" numeric,
  "Squat2Kg" numeric,
  "Squat3Kg" numeric,
  "Squat4Kg" numeric,
  "Best3SquatKg" numeric,
  "Bench1Kg" numeric,
  "Bench2Kg" numeric,
  "Bench3Kg" numeric,
  "Bench4Kg" numeric,
  "Best3BenchKg" numeric,
  "Deadlift1Kg" numeric,
  "Deadlift2Kg" numeric,
  "Deadlift3Kg" numeric,
  "Deadlift4Kg" numeric,
  "Best3DeadliftKg" numeric,
  "TotalKg" numeric
);

CREATE TABLE "Meet" (
  "meet_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "MeetCountry" varchar(255),
  "MeetState" varchar(255),
  "MeetName" varchar(255),
  "Date" date
);

CREATE TABLE "Performance" (
  "performance_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "athlete_id" int,
  "meet_id" int,
  "Place" int,
  "Wilks" numeric,
  "Glossbrenner" numeric,
  "Tested" boolean
);

ALTER TABLE "Lift" ADD FOREIGN KEY ("athlete_id") REFERENCES "Athlete" ("athlete_id");

ALTER TABLE "Lift" ADD FOREIGN KEY ("event_id") REFERENCES "Event" ("event_id");

ALTER TABLE "Lift" ADD FOREIGN KEY ("equipment_id") REFERENCES "Equipment" ("equipment_id");

ALTER TABLE "Lift" ADD FOREIGN KEY ("division_id") REFERENCES "Division" ("division_id");

ALTER TABLE "Lift" ADD FOREIGN KEY ("weightclass_id") REFERENCES "WeightClass" ("weightclass_id");

ALTER TABLE "Performance" ADD FOREIGN KEY ("athlete_id") REFERENCES "Athlete" ("athlete_id");

ALTER TABLE "Performance" ADD FOREIGN KEY ("meet_id") REFERENCES "Meet" ("meet_id");
